export interface DessertSize {
  id: string
  label: string
  price: number
}

export interface Dessert {
  id: string
  name: string
  category: string
  price: number
  priceLabel?: string
  rating: number
  image: string
  description?: string
  sizes?: DessertSize[]
}

export const categories = [
  'All',
  'Brownies',
  'Jar Cakes',
  'Cookies',
  'Cupcakes',
  'Tiramisu',
  'Bento Cakes',
  'Cakes',
  'Mini Tubs',
  'Tin Cakes',
  'Cake Shooters',
]

export const desserts: Dessert[] = [
  // Brownies - with sizes
  {
    id: 'brownie-signature',
    name: 'Signature Brownie',
    category: 'Brownies',
    price: 750,
    rating: 4.9,
    image: '/images/brownie-signature.jpg',
    description: 'Our classic fudgy brownie with intense chocolate flavor',
    sizes: [
      { id: 'brownie-signature-8', label: 'Box of 8', price: 750 },
      { id: 'brownie-signature-12', label: 'Box of 12', price: 950 },
    ],
  },
  {
    id: 'brownie-kitkat-oreo',
    name: 'Kitkat Oreo Brownie',
    category: 'Brownies',
    price: 850,
    rating: 4.8,
    image: '/images/brownie-kitkat.jpg',
    description: 'Loaded with Kitkat and Oreo chunks',
    sizes: [
      { id: 'brownie-kitkat-oreo-8', label: 'Box of 8', price: 850 },
      { id: 'brownie-kitkat-oreo-12', label: 'Box of 12', price: 1050 },
    ],
  },
  {
    id: 'brownie-nutella-biscoff',
    name: 'Nutella Biscoff Brownie',
    category: 'Brownies',
    price: 900,
    rating: 4.9,
    image: '/images/brownie-nutella.jpg',
    description: 'Swirled with Nutella and topped with Biscoff crumbs',
    sizes: [
      { id: 'brownie-nutella-biscoff-8', label: 'Box of 8', price: 900 },
      { id: 'brownie-nutella-biscoff-12', label: 'Box of 12', price: 1100 },
    ],
  },
  {
    id: 'brownie-walnuts',
    name: 'Walnut Brownie',
    category: 'Brownies',
    price: 950,
    rating: 4.7,
    image: '/images/brownie-walnut.jpg',
    description: 'Classic brownie studded with crunchy walnuts',
    sizes: [
      { id: 'brownie-walnuts-8', label: 'Box of 8', price: 950 },
      { id: 'brownie-walnuts-12', label: 'Box of 12', price: 1200 },
    ],
  },
  // Jar Cakes - no sizes
  {
    id: 'jar-milk-choc',
    name: 'Milk Chocolate Jar',
    category: 'Jar Cakes',
    price: 200,
    rating: 4.6,
    image: '/images/jar-chocolate.jpg',
    description: 'Layered milk chocolate cake in a jar',
  },
  {
    id: 'jar-dark-choc',
    name: 'Dark Chocolate Jar',
    category: 'Jar Cakes',
    price: 200,
    rating: 4.7,
    image: '/images/jar-dark.jpg',
    description: 'Rich dark chocolate layers',
  },
  {
    id: 'jar-white-choc',
    name: 'White Chocolate Jar',
    category: 'Jar Cakes',
    price: 200,
    rating: 4.5,
    image: '/images/jar-white.jpg',
    description: 'Creamy white chocolate delight',
  },
  {
    id: 'jar-red-velvet',
    name: 'Red Velvet Jar',
    category: 'Jar Cakes',
    price: 210,
    rating: 4.8,
    image: '/images/jar-redvelvet.jpg',
    description: 'Classic red velvet with cream cheese',
  },
  {
    id: 'jar-triple-choc',
    name: 'Triple Chocolate Jar',
    category: 'Jar Cakes',
    price: 230,
    rating: 4.9,
    image: '/images/jar-triple.jpg',
    description: 'Three layers of chocolate heaven',
  },
  // Cookies
  {
    id: 'cookie-choc-chunk',
    name: 'Chocolate Chunk Cookies',
    category: 'Cookies',
    price: 660,
    priceLabel: 'Box of 6',
    rating: 4.7,
    image: '/images/cookie-chocolate.jpg',
    description: 'Loaded with premium chocolate chunks',
  },
  {
    id: 'cookie-nutella',
    name: 'Nutella Cookies',
    category: 'Cookies',
    price: 750,
    priceLabel: 'Box of 6',
    rating: 4.8,
    image: '/images/cookie-nutella.jpg',
    description: 'Filled with gooey Nutella center',
  },
  {
    id: 'cookie-vanilla',
    name: 'Vanilla Cookies',
    category: 'Cookies',
    price: 270,
    priceLabel: '20-22 cookies',
    rating: 4.5,
    image: '/images/cookie-vanilla.jpg',
    description: 'Classic buttery vanilla cookies',
  },
  // Cupcakes
  {
    id: 'cupcake-chocolate',
    name: 'Chocolate Cupcakes',
    category: 'Cupcakes',
    price: 500,
    priceLabel: 'Box of 6',
    rating: 4.6,
    image: '/images/cupcake-chocolate.jpg',
    description: 'Moist chocolate with swirled frosting',
  },
  {
    id: 'cupcake-vanilla',
    name: 'Vanilla Cupcakes',
    category: 'Cupcakes',
    price: 500,
    priceLabel: 'Box of 6',
    rating: 4.6,
    image: '/images/cupcake-vanilla.jpg',
    description: 'Light and fluffy with vanilla buttercream',
  },
  {
    id: 'cupcake-cookies-cream',
    name: 'Cookies & Cream Cupcakes',
    category: 'Cupcakes',
    price: 550,
    priceLabel: 'Box of 6',
    rating: 4.7,
    image: '/images/cupcake-oreo.jpg',
    description: 'Topped with Oreo crumbs and cream',
  },
  {
    id: 'cupcake-nutella',
    name: 'Nutella Cupcakes',
    category: 'Cupcakes',
    price: 700,
    priceLabel: 'Box of 6',
    rating: 4.8,
    image: '/images/cupcake-nutella.jpg',
    description: 'Filled and topped with Nutella',
  },
  {
    id: 'cupcake-biscoff',
    name: 'Biscoff Cupcakes',
    category: 'Cupcakes',
    price: 700,
    priceLabel: 'Box of 6',
    rating: 4.8,
    image: '/images/cupcake-biscoff.jpg',
    description: 'Biscoff spread swirled throughout',
  },
  // Tiramisu
  {
    id: 'tiramisu-classic',
    name: 'Classic Tiramisu',
    category: 'Tiramisu',
    price: 350,
    rating: 4.9,
    image: '/images/tiramisu-classic.jpg',
    description: 'Traditional Italian coffee-soaked delight',
  },
  {
    id: 'tiramisu-biscoff',
    name: 'Biscoff Tiramisu',
    category: 'Tiramisu',
    price: 400,
    rating: 4.9,
    image: '/images/tiramisu-biscoff.jpg',
    description: 'Biscoff twist on the classic',
  },
  // Bento Cakes
  {
    id: 'bento-vanilla',
    name: 'Vanilla Bento Cake',
    category: 'Bento Cakes',
    price: 450,
    rating: 4.7,
    image: '/images/bento-vanilla.jpg',
    description: 'Mini customizable vanilla cake',
  },
  {
    id: 'bento-chocolate',
    name: 'Chocolate Bento Cake',
    category: 'Bento Cakes',
    price: 450,
    rating: 4.7,
    image: '/images/bento-chocolate.jpg',
    description: 'Mini customizable chocolate cake',
  },
  // Cakes - with sizes
  {
    id: 'cake-custom',
    name: 'Custom Cake',
    category: 'Cakes',
    price: 850,
    rating: 4.8,
    image: '/images/cake-custom.jpg',
    description: 'Customizable cake - contact for flavours',
    sizes: [
      { id: 'cake-half-kg', label: 'Half kg', price: 850 },
      { id: 'cake-one-kg', label: '1 kg', price: 1700 },
    ],
  },
  // Mini Tubs
  {
    id: 'minitub-chocolate',
    name: 'Chocolate Mini Tub',
    category: 'Mini Tubs',
    price: 350,
    priceLabel: 'Min. 2',
    rating: 4.6,
    image: '/images/minitub-chocolate.jpg',
    description: 'Creamy chocolate in a tub',
  },
  {
    id: 'minitub-vanilla',
    name: 'Vanilla Mini Tub',
    category: 'Mini Tubs',
    price: 350,
    priceLabel: 'Min. 2',
    rating: 4.6,
    image: '/images/minitub-vanilla.jpg',
    description: 'Silky vanilla in a tub',
  },
  {
    id: 'minitub-biscoff',
    name: 'Biscoff Mini Tub',
    category: 'Mini Tubs',
    price: 400,
    priceLabel: 'Min. 2',
    rating: 4.8,
    image: '/images/minitub-biscoff.jpg',
    description: 'Biscoff flavored mini tub',
  },
  {
    id: 'minitub-nutella',
    name: 'Nutella Mini Tub',
    category: 'Mini Tubs',
    price: 400,
    priceLabel: 'Min. 2',
    rating: 4.8,
    image: '/images/minitub-nutella.jpg',
    description: 'Nutella swirled mini tub',
  },
  {
    id: 'minitub-hazelnut',
    name: 'Hazelnut Crunch Mini Tub',
    category: 'Mini Tubs',
    price: 420,
    priceLabel: 'Min. 2',
    rating: 4.7,
    image: '/images/minitub-hazelnut.jpg',
    description: 'Crunchy hazelnut bits throughout',
  },
  // Tin Cakes
  {
    id: 'tin-chocolate',
    name: 'Chocolate Tin Cake',
    category: 'Tin Cakes',
    price: 750,
    rating: 4.7,
    image: '/images/tin-chocolate.jpg',
    description: 'Layered chocolate cake in a tin',
  },
  {
    id: 'tin-vanilla',
    name: 'Vanilla Tin Cake',
    category: 'Tin Cakes',
    price: 750,
    rating: 4.7,
    image: '/images/tin-vanilla.jpg',
    description: 'Layered vanilla cake in a tin',
  },
  {
    id: 'tin-biscoff',
    name: 'Biscoff Tin Cake',
    category: 'Tin Cakes',
    price: 850,
    rating: 4.8,
    image: '/images/tin-biscoff.jpg',
    description: 'Biscoff flavored tin cake',
  },
  {
    id: 'tin-nutella',
    name: 'Nutella Tin Cake',
    category: 'Tin Cakes',
    price: 850,
    rating: 4.8,
    image: '/images/tin-nutella.jpg',
    description: 'Nutella layered tin cake',
  },
  {
    id: 'tin-hazelnut',
    name: 'Hazelnut Crunch Tin Cake',
    category: 'Tin Cakes',
    price: 900,
    rating: 4.8,
    image: '/images/tin-hazelnut.jpg',
    description: 'Crunchy hazelnut tin cake',
  },
  // Cake Shooters
  {
    id: 'shooter-french-vanilla',
    name: 'French Vanilla Shooter',
    category: 'Cake Shooters',
    price: 100,
    priceLabel: 'Min. 5',
    rating: 4.5,
    image: '/images/shooter-vanilla.jpg',
    description: 'Mini vanilla cake in a shot glass',
  },
  {
    id: 'shooter-pineapple',
    name: 'Pineapple Shooter',
    category: 'Cake Shooters',
    price: 100,
    priceLabel: 'Min. 5',
    rating: 4.5,
    image: '/images/shooter-pineapple.jpg',
    description: 'Tropical pineapple cake shooter',
  },
  {
    id: 'shooter-classic-choc',
    name: 'Classic Chocolate Shooter',
    category: 'Cake Shooters',
    price: 100,
    priceLabel: 'Min. 5',
    rating: 4.6,
    image: '/images/shooter-chocolate.jpg',
    description: 'Rich chocolate cake shooter',
  },
  {
    id: 'shooter-lotus-biscoff',
    name: 'Lotus Biscoff Shooter',
    category: 'Cake Shooters',
    price: 125,
    priceLabel: 'Min. 5',
    rating: 4.7,
    image: '/images/shooter-biscoff.jpg',
    description: 'Biscoff flavored cake shooter',
  },
  {
    id: 'shooter-hazelnut-crunch',
    name: 'Hazelnut Crunch Shooter',
    category: 'Cake Shooters',
    price: 125,
    priceLabel: 'Min. 5',
    rating: 4.7,
    image: '/images/shooter-hazelnut.jpg',
    description: 'Crunchy hazelnut cake shooter',
  },
  {
    id: 'shooter-nutella',
    name: 'Nutella Shooter',
    category: 'Cake Shooters',
    price: 130,
    priceLabel: 'Min. 5',
    rating: 4.8,
    image: '/images/shooter-nutella.jpg',
    description: 'Nutella filled cake shooter',
  },
]
